## Self collision parameters for node cob_obstacle_distance component_name:=arm
self_collision_frames: {
    torso_1_link : [arm_forearm_link, arm_upper_arm_link, arm_wrist_2_link],
    torso_0_link : [arm_forearm_link, arm_upper_arm_link, arm_wrist_2_link],
    base_link : [arm_forearm_link, arm_upper_arm_link, arm_wrist_2_link],
    tower_base_link : [arm_forearm_link, arm_wrist_2_link],
}

