## Self collision parameters for node cob_obstacle_distance component_name:=arm_right

## Left: The self collision link that shall be represented like an obstacle
## Right: The link that shall be taken for collision checking between self collision link and arm right link.
## ATTENTION: self-collision for the component frame is only active when this link has been registered before!!!
self_collision_frames: {
    head_3_link : [arm_right_3_link, arm_right_4_link, arm_right_5_link, arm_right_6_link, arm_right_7_link],
    torso_3_link : [arm_right_4_link, arm_right_5_link, arm_right_6_link, arm_right_7_link],
    base_link : [arm_right_5_link, arm_right_6_link, arm_right_7_link],
}

